---
plugin: gcp_compute
zones: europe-west6-a
projects: java-243611
filters: 
  - machineName: back
service_account_file: "/home/dr_trem86/secrets/java-243611-6d1d9066ee2b.json"
auth_kind: serviceaccount
keyed_groups:
  # Create groups from GCE labels
  - prefix: gcp
    key: back
hostnames:
  # List host by name instead of the default public ip
  - name
compose:
  # Set an inventory parameter to use the Public IP address to connect to the host
  # For Private ip use "networkInterfaces[0].networkIP"
  ansible_host: networkInterfaces[0].accessConfigs[0].natIP