---
- name: front_servers
  hosts: back_server
  become: yes

  tasks:

  - name: install openjdk-8-jdk
    shell: "apt install -y openjdk-8-jdk"

  - name: maven
    shell: "apt -y install maven"

  - name: clone repo and install mvnw
    shell: "git clone https://github.com/pribytkovskiy/demo3.git && cd ./demo3/src/backend && sh ./mvnw install"

  - name: mvnw start
    shell: "sh ./mvnw spring-boot:run -f ./server/"
