---
- name: instance_facts
  gcp_compute_instance_facts:
    zone: europe-west6-a
    project: java-243611
    auth_kind: serviceaccount
    service_account_file: "/home/dr_trem86/secrets/java-243611-6d1d9066ee2b.json"
    state: facts

- name: front_servers
  hosts: back
  become: yes

  tasks:
  - name: install nodejs
    shell: "curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash - && apt-get install -y nodejs"

  - name: clone repo and install npm
    shell: "git clone https://github.com/pribytkovskiy/demo3.git && cd ./demo3/src/frontend && npm install"

  - name: npm install pm2 -g
    shell: "npm install pm2 -g"
    
  - name: npm start
    shell: "cd ./demo3/src/frontend && pm2 start npm -- start"
