---
- name: back_server
  hosts: back_server
  become: yes

  tasks:
  - name: apt update
    shell: "apt update"

  - name: clone repo
    shell: "git clone https://github.com/pribytkovskiy/demo3.git"

# cloud_sql_proxy

  - name: download cloud_sql_proxy
    shell: "wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy"

  - name: dir
    shell: "realpath cloud_sql_proxy"

  - name: copy cloud-sql-proxy
    copy:
      remote_src: yes
      src: ~/cloud_sql_proxy
      dest: /usr/local/bin/cloud_sql_proxy

  - name: make run cloud-sql-proxy
    shell: "chmod +x /usr/local/bin/cloud_sql_proxy"

  - name: copy cloud-sql-proxy.service
    copy:
      remote_src: yes
      src: ~/demo3/support/db/cloud-sql-proxy.service
      dest: /etc/systemd/system/cloud-sql-proxy.service

  - name: copy credential_file
    copy:
      src: /var/lib/jenkins/.ssh/java-243611-5d8bde4edca0.json
      dest: ./java-243611-5d8bde4edca0.json

  - name: systemctl daemon-reload
    shell: "systemctl daemon-reload"

  - name: start daemon cloud-sql-proxy
    shell: "service cloud-sql-proxy start"

# back

  - name: install openjdk-8-jdk
    shell: "apt install -y openjdk-8-jdk"

  - name: maven
    shell: "apt -y install maven"

  - name: install mvnw
    shell: "cd ./demo3/src/backend && sh ./mvnw install"

  - name: copy java_app.service
    copy:
      remote_src: yes
      src: ~/demo3/support/back/java_app.service
      dest: /etc/systemd/system/java_app.service

  - name: make run mvnw
    shell: "chmod +x /root/demo3/src/backend/mvnw"

  - name: systemctl daemon-reload
    shell: "systemctl daemon-reload"

  - name: start daemon java_app
    shell: "service java_app start"
